function createfigure(YMatrix1, YMatrix2, YMatrix3)
%CREATEFIGURE(YMatrix1, YMatrix2, YMatrix3)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data

%  Auto-generated by MATLAB on 29-Jul-2019 17:20:47

% Create figure
figure;

% Create subplot
subplot1 = subplot(1,3,1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'LineWidth',1,'Color',[0 0 0]);
set(plot1(1),'DisplayName','Unshielded','LineStyle','--');
set(plot1(2),'DisplayName','Shielded');

% Create ylabel
ylabel({'Normalized Count'});

% Create xlabel
xlabel({'x cells'});

% Create title
title({'Front'});

box(subplot1,'on');
axis(subplot1,'square');
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'Location','best');

% Create subplot
subplot2 = subplot(1,3,2);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(YMatrix2,'LineWidth',1,'Color',[0 0 0]);
set(plot2(1),'DisplayName','Unshielded','LineStyle','--');
set(plot2(2),'DisplayName','Shielded');

% Create ylabel
ylabel({'Normalized Count'});

% Create xlabel
xlabel({'x cells'});

% Create title
title({'Middle'});

box(subplot2,'on');
axis(subplot2,'square');
% Create legend
legend2 = legend(subplot2,'show');
set(legend2,'Location','best');

% Create subplot
subplot3 = subplot(1,3,3);
hold(subplot3,'on');

% Create multiple lines using matrix input to plot
plot3 = plot(YMatrix3,'LineWidth',1,'Color',[0 0 0]);
set(plot3(1),'DisplayName','Unshielded','LineStyle','--');
set(plot3(2),'DisplayName','Shielded');

% Create ylabel
ylabel({'Normalized Count'});

% Create xlabel
xlabel({'x cells'});

% Create title
title({'Back'});

box(subplot3,'on');
axis(subplot3,'square');
% Create legend
legend3 = legend(subplot3,'show');
set(legend3,'Location','best');

